### ISSUE TITLE
_link hrefs are url encoded - bug or user error?

### ISSUE THREAD

**Issue by epikhighs** [bleupen/halacious#44]
Hi,

I noticed that (in particular) curly brace characters are url encoded (%7b) in the href of _link objects.  Is there a way to make halacious not url encode the _link's href?

Thanks.

**Comment by bleupen** [comment]
sorry for the radio silence. working on this now.

**Comment by bleupen** [comment]
the problem is that I (unwisely) chose {} to delimit server side template expressions. what about this approach: if "templated" is set to true on the link, I will disable server-side template expansion and assume that the link should be transmitted as-is to the client (relative paths will still be resolved).

**Comment by epikhighs** [comment]
@bleupen 

Hi!

I think your proposed solution makes sense to me.  The one potential downside is that you wouldn't be able to mix both server-side template expansion with client-side expansion.  Maybe that might be important to some people?  

Thanks.
