### ISSUE TITLE
Array of links in _links ?

### ISSUE THREAD

**Issue by picsoung** [bleupen/halacious#53]
Hi,
I am fairly new to HAL and I found this plugin pretty useful to get started.

I basically want to achieve this:

```javascript
{
    "_links": {
      "items": [{
          "href": "/first_item"
      },{
          "href": "/second_item"
      }]
    }
}
```
as described under `Representing Multiple Links With The Same Relation` [here](http://stateless.co/hal_specification.html)

How could I do this using halacious ?

in my database this is stored as 

```
items:[
   {
     "name":"first_item",
     "id":"first_item_id"
   },
   {
     "name":"second_item",
     "id":"second_item_id"
    }
]
```

Thanks

**Comment by bleupen** [comment]
Hi there,

Multiple links with the same rel can be done but not by using the configuration short-hand. You'll have to use a prepare function on the route or a toHal() method on the returned entity. I added a full example to the examples folder, but here's the idea:

```javascript
    // route definition
    // ...
    plugins: {
        hal: {
            prepare: function (rep, next) {
                var employees = rep.entity.employees;

                // adding multiple links with the same rel will create an array of links in the payload

                // link by route id
                rep.link('mco:employee', rep.route('employee.lookup', employees[0]));

                // or by relative path
                rep.link('mco:employee', '../../employees/'+ employees[1].id);

                // or by absolute path
                rep.link('mco:employee', '/employees/'+ employees[2].id);

                next();
            }
        }
    }
```

In reality, this use case rarely comes up for me because most, if not all, of my would-be link collections are mapped to their collection resource urls.

So, instead of doing this:
 ``` >> GET /company/100``` 
```javascript
{
   "_links": {
      "employee": [ { "href": "/employees/100"  }, { "href": "/employees/101" } ]
   }
}
```

i would do this:

```>> GET /company/100```
```javascript```
{
   "_links": { "employees": { "href": "/company/100/employees" }}
}
```
where ```/company/100/employees``` is a query-able collection resource returning a HAL entity with embedded employee items.

Obviously, the first approach makes more sense if you are returning a small fixed set of links.

**Comment by picsoung** [comment]
Thanks @bleupen for your answer :smile: 

Makes for sense to me now.
I have only a small set (max of 4) of links, so I would go with the first option.

I also want to reduce number of calls, the second approach increase number of calls.

Thanks again :)
