### ISSUE TITLE
Hapi 9.x compatibility

### ISSUE THREAD

**Issue by brabster** [bleupen/halacious#64]
There seems to be an incompatible change in Hapi starting at 9.0.0.  Unable to run tests from this version with server.views being undefined

**Comment by 4eek** [comment]
Please see https://github.com/hapijs/hapi/issues/2706

Comment by @mtharrison ...

"Hi! It looks like you're using hapi 9 where view rendering is now enabled by an optional plugin (vision) rather than being bundled with core. To use server.views, reply.view and friends you need to register it: https://github.com/hapijs/vision

See release notes for hapi 9 for other changes here: #2682"

**Comment by bleupen** [comment]
Just confirmed halacious works with Hapi 9 if you install and register vision. My plan for halacious is to explicitly declare a dependency on vision via `server.register()` (leaving to the user the task of installing and configuring vision) and to update the tests / examples to work out of the box. Sound good?

**Comment by 4eek** [comment]
:+1:

**Comment by brabster** [comment]
Sounds like a plan... I'd only offer whether it's worth catching and logging if vision's not available and if not then just skipping the views setup? Think most of the functionality would still work fine?

**Comment by bleupen** [comment]
just pushed up a hapi 9 branch with progressive support for vision / rels documentation. i have tested with hapi 8 and 9 here and everything seems to work fine. would love it if somebody else could try it in their environment before i cut a release. thanks!
